# PVC and PV
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mssqldb/"
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssqldb
spec:
  selector:
    matchLabels:
      app: mssqldb
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mssqldb
    spec:
      containers:
      - name: mssqldb
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          requests:
            cpu: 500m
            memory: 4000M

        env:
          - name: MSSQL_PID
            value: "Standard"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "yourStrong(!)Password"
        volumeMounts:
          - name: db-persistent-storage
            mountPath: /var/opt/mssql
      volumes:
        - name: db-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: mssql-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: mssqldb
spec:
  selector:
    app: mssqldb
  ports:
    - name: mssql-port
      port: 1433
      targetPort: 1433
      nodePort: 30070
  type: NodePort